//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssjswebapi11032020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Member_Master
    {
        public int id { get; set; }
        public string code { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string dob { get; set; }
        public string blood_group { get; set; }
        public string pancard_no { get; set; }
        public string votingcard_no { get; set; }
        public string aadharcard_no { get; set; }
        public string is_head_of_fimily { get; set; }
        public string HOF_id { get; set; }
        public string HOF_name { get; set; }
        public string HOF_relation { get; set; }
        public string isalive { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
