//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssjswebapi11032020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fund_type
    {
        public int id { get; set; }
        public string english_fund_name { get; set; }
        public string gujarati_fund_name { get; set; }
        public string istithi_based { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
